Server:
  Host: 127.0.0.1
  Port: 10240
  Dev: true
  PortPoolBegin: 10241
  PortPoolSize: 10
Mongo:
  Host: 127.0.0.1
  Port: 12345
  User: user
  Password: password
  Name: bug
Violet:
  ClientID: 1234567890
  ClientKey: 12345567890
  ServerHost: https://oauth.xmatrix.studio/api/v2
  LoginURL: https://oauth.xmatrix.studio/api/v2